version: '3.8'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongo:27017/formdb
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
